name=RV003USB
version=0.1.0
author=CNLohr
maintainer=lopple
sentence=Experimental USB HID keyboard support based on rv003usb for CH32V003.
paragraph=Provides experimental USB HID keyboard support using the rv003usb low-speed software USB implementation.
category=Communication
url=https://github.com/cnlohr/rv003usb
architectures=ch32v
